import { StyleSheet } from 'react-native';
import { COLORS, SPACING, TYPOGRAPHY } from '../../constants';
import { getImageDimensions, getSafeMargins, hp, rf, wp } from '../../utils';

const margins = getSafeMargins();
const imageDimensions = getImageDimensions(16 / 9);
export const MAP_HEIGHT = hp(25);

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollView: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: margins.horizontal,
  },
  errorText: {
    fontSize: rf(16),
    color: COLORS.error,
    textAlign: 'center',
    marginVertical: wp(4),
  },
  imageContainer: {
    height: imageDimensions.height,
    position: 'relative',
  },
  headerImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  backButton: {
    position: 'absolute',
    top: wp(4),
    left: wp(4),
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
    zIndex: 10,
  },
  favoriteButton: {
    position: 'absolute',
    top: wp(4),
    right: wp(4),
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
    zIndex: 10,
  },
  content: {
    flex: 1,
    backgroundColor: COLORS.background,
    marginTop: -wp(5),
    borderTopLeftRadius: wp(5),
    borderTopRightRadius: wp(5),
    paddingTop: SPACING.lg,
  },
  titleSection: {
    paddingHorizontal: margins.horizontal,
    marginBottom: wp(4),
  },
  title: {
    fontSize: rf(24),
    color: COLORS.textPrimary,
    marginBottom: wp(2),
    fontWeight: '700',
    lineHeight: rf(30),
  },
  statusContainer: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.success,
    paddingHorizontal: wp(3),
    paddingVertical: wp(1),
    borderRadius: wp(5),
  },
  status: {
    fontSize: rf(12),
    color: COLORS.white,
    fontWeight: '600',
  },
  detailsSection: {
    paddingHorizontal: margins.horizontal,
    marginBottom: wp(4),
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: SPACING.md,
  },
  detailContent: {
    flex: 1,
    marginLeft: SPACING.md,
  },
  detailLabel: {
    ...TYPOGRAPHY.caption,
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    fontWeight: '600',
    marginBottom: 2,
  },
  detailValue: {
    ...TYPOGRAPHY.body1,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  detailSubvalue: {
    ...TYPOGRAPHY.body2,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  mapSection: {
    marginBottom: SPACING.lg,
    paddingHorizontal: SPACING.lg,
  },
  mapHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  mapTitle: {
    ...TYPOGRAPHY.caption,
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    fontWeight: '600',
    marginLeft: SPACING.md,
  },
  mapContainer: {
    height: 200,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  map: {
    flex: 1,
  },
  mapPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.gray50,
    paddingVertical: SPACING.xl,
  },
  mapPlaceholderText: {
    ...TYPOGRAPHY.h4,
    color: COLORS.textPrimary,
    fontWeight: '600',
    marginTop: SPACING.md,
    textAlign: 'center',
  },
  mapPlaceholderSubtext: {
    ...TYPOGRAPHY.body2,
    color: COLORS.textSecondary,
    marginTop: SPACING.xs,
    textAlign: 'center',
  },
  directionsButton: {
    position: 'absolute',
    bottom: SPACING.md,
    right: SPACING.md,
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: 20,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  directionsButtonText: {
    ...TYPOGRAPHY.caption,
    color: COLORS.white,
    fontWeight: '600',
    marginLeft: SPACING.xs,
  },
  descriptionSection: {
    paddingHorizontal: SPACING.lg,
    marginBottom: SPACING.lg,
  },
  sectionTitle: {
    ...TYPOGRAPHY.h3,
    color: COLORS.textPrimary,
    fontWeight: '600',
    marginBottom: SPACING.md,
  },
  description: {
    ...TYPOGRAPHY.body1,
    color: COLORS.textSecondary,
    lineHeight: 24,
  },
  readMoreText: {
    ...TYPOGRAPHY.body2,
    color: COLORS.primary,
    fontWeight: '600',
    marginTop: SPACING.sm,
  },
  venueName: {
    ...TYPOGRAPHY.h3,
    color: COLORS.textPrimary,
    fontWeight: '600',
    marginTop: SPACING.sm,
    textAlign: 'center',
  },
  venueAddress: {
    ...TYPOGRAPHY.body2,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginTop: SPACING.xs,
    marginBottom: SPACING.lg,
  },
  directionsText: {
    ...TYPOGRAPHY.button,
    color: COLORS.white,
    marginLeft: SPACING.xs,
  },
  actionSection: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.lg,
    gap: SPACING.md,
  },
  ticketButton: {},
});
